// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Andrea De Murtas

#pragma once

#include <juce_dsp/juce_dsp.h>
#include <vector>

namespace galdr
{

// Morphing wavetable: 32 frames sweeping sine -> triangle -> saw -> square -> "grim"
// (an inharmonic metallic spectrum). Band-limited via mip levels generated by IFFT,
// one per octave, so high notes read tables with fewer harmonics and never alias.
class Wavetable
{
public:
    static constexpr int tableSize = 2048;
    static constexpr int numFrames = 32;
    static constexpr int numMips   = 9; // mip m allows 1024 >> m harmonics

    Wavetable() { generate(); }

    static const Wavetable& global()
    {
        static const Wavetable instance;
        return instance;
    }

    int mipForDt(float dt) const
    {
        const float maxAllowed = 0.5f / juce::jmax(1.0e-6f, dt);
        int mip = 0;
        while (mip < numMips - 1 && (float) (1024 >> mip) > maxAllowed)
            ++mip;
        return mip;
    }

    float sample(int mip, float framePos, float phase) const
    {
        const float f = juce::jlimit(0.0f, 1.0f, framePos) * (float) (numFrames - 1);
        const int f0 = juce::jmin(numFrames - 2, (int) f);
        const float ff = f - (float) f0;

        const float idx = phase * (float) tableSize;
        const int i0 = juce::jmin(tableSize - 1, (int) idx);
        const float fi = idx - (float) i0;

        auto read = [this, mip, i0, fi](int frame)
        {
            const float* d = frameData(mip, frame);
            return d[i0] + fi * (d[i0 + 1] - d[i0]);
        };
        return read(f0) + ff * (read(f0 + 1) - read(f0));
    }

private:
    const float* frameData(int mip, int frame) const
    {
        return data.data() + ((size_t) mip * numFrames + (size_t) frame) * (tableSize + 1);
    }

    static float harmonicAmp(float m, int h)
    {
        auto sine = [](int hh) { return hh == 1 ? 1.0f : 0.0f; };
        auto tri  = [](int hh) { return (hh & 1) ? 1.0f / (float) (hh * hh) : 0.0f; };
        auto saw  = [](int hh) { return 1.0f / (float) hh; };
        auto sqr  = [](int hh) { return (hh & 1) ? 1.0f / (float) hh : 0.0f; };
        auto grim = [](int hh)
        {
            float a = 1.0f / std::pow((float) hh, 0.6f);
            a *= 0.35f + 0.65f * std::abs(std::sin((float) hh * 1.7f));
            if (hh == 7 || hh == 11 || hh == 13 || hh == 19)
                a *= 2.5f;
            return a;
        };

        const float pos = juce::jlimit(0.0f, 1.0f, m) * 4.0f;
        const int seg = juce::jmin(3, (int) pos);
        const float t = pos - (float) seg;
        float a0 = 0.0f, a1 = 0.0f;
        switch (seg)
        {
            case 0:  a0 = sine(h); a1 = tri(h);  break;
            case 1:  a0 = tri(h);  a1 = saw(h);  break;
            case 2:  a0 = saw(h);  a1 = sqr(h);  break;
            default: a0 = sqr(h);  a1 = grim(h); break;
        }
        return a0 + t * (a1 - a0);
    }

    void generate()
    {
        data.resize((size_t) numMips * numFrames * (tableSize + 1));
        juce::dsp::FFT fft(11);
        std::vector<float> work((size_t) 2 * tableSize);

        for (int frame = 0; frame < numFrames; ++frame)
        {
            const float m = (float) frame / (float) (numFrames - 1);
            for (int mip = 0; mip < numMips; ++mip)
            {
                const int maxH = 1024 >> mip;
                std::fill(work.begin(), work.end(), 0.0f);
                for (int h = 1; h <= maxH && h < tableSize / 2; ++h)
                    work[(size_t) (2 * h + 1)] = -harmonicAmp(m, h);

                fft.performRealOnlyInverseTransform(work.data());

                float peak = 1.0e-9f;
                for (int i = 0; i < tableSize; ++i)
                    peak = juce::jmax(peak, std::abs(work[(size_t) i]));

                float* dst = data.data() + ((size_t) mip * numFrames + (size_t) frame) * (tableSize + 1);
                for (int i = 0; i < tableSize; ++i)
                    dst[i] = work[(size_t) i] / peak;
                dst[tableSize] = dst[0];
            }
        }
    }

    std::vector<float> data;
};

} // namespace galdr
